#!/usr/bin/env bash

# Colors
RESET=$(tput sgr0)
# shellcheck disable=SC2034
RED=$(tput setaf 1)
# shellcheck disable=SC2034
GREEN=$(tput setaf 2)
# shellcheck disable=SC2034
YELLOW=$(tput setaf 3)
# shellcheck disable=SC2034
BLUE=$(tput setaf 4)
# shellcheck disable=SC2034
MAGENTA=$(tput setaf 5)
# shellcheck disable=SC2034
CYAN=$(tput setaf 6)
# shellcheck disable=SC2034
ITALIC=$(tput sitm)
# shellcheck disable=SC2034
BOLD=$(tput bold)

set -e
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "${YELLOW}======================================================================${RESET}"
echo "${YELLOW}1. Executing install.pre ...${RESET}"

[ -f "${BASEDIR}/install.pre" ] && "${BASEDIR}/install.pre"

echo "${YELLOW}======================================================================${RESET}"
echo "${YELLOW}2. Executing install ...${RESET}"

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

echo "${YELLOW}======================================================================${RESET}"
echo "${YELLOW}3. Executing install.post ...${RESET}"

[ -f "${BASEDIR}/install.post" ] && "${BASEDIR}/install.post"

echo "${YELLOW}======================================================================${RESET}"

################################################################################
# vim: ft=bash syntax=bash cc=120 tw=119 ts=4 sw=4 sts=4 et sr
