#!/usr/bin/env bash

# mkdir ~/.dotfiles.local &> /dev/null
# pushd ~/.dotfiles.local

# create symlinks from ~/.dotfiles.local/ to ~/
if [ -d ~/.dotfiles.local ]; then
    for file in $(find ~/.dotfiles.local -type f); do
        ln -sf $file "$(echo "$file" | sed 's/\.dotfiles\.local\///')"
    done
fi
