#!/usr/bin/env bash

SHELL_NAME=$(basename $SHELL)

# create ${SHELL_NAME}rc.local if not exists
if [ ! -f ~/.${SHELL_NAME}rc.local ]; then
    touch ~/.${SHELL_NAME}rc.local
fi

# use commands from zsh-abbr abbreviations
if [ ${SHELL_NAME} == "bash" ]; then
    sed 's/^abbr/alias/' ~/.dotfiles/configs/zsh-plugins/zsh-abbr/abbreviations > ~/.bashrc.abbr.sh
fi

# delete all broken symlinks
CLEAN_DIRS=( ~ ~/bin ~/.config/nvim ~/.config/nvim/lua)
for CLEAN_DIR in "${CLEAN_DIRS[@]}"; do
    if [ -d ${CLEAN_DIR} ]; then
        find ${CLEAN_DIR} -maxdepth 1 -type l -exec sh -c 'for x; do [ -e "$x" ] || rm "$x"; done' _ {} +
    fi
done
