#!/usr/bin/env bash

mkdir ~/.dotfiles.local &> /dev/null
pushd ~/.dotfiles.local &> /dev/null

echo "Use proxy?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) touch .flag.proxy &> /dev/null; break;;
        No ) rm .flag.proxy &> /dev/null; break;;
    esac
done

echo "Enable tmux at login?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) touch .flag.tmux_auto_launch &> /dev/null; break;;
        No ) rm .flag.tmux_auto_launch &> /dev/null; break;;
    esac
done
