#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
"""This is the example module.

This module does stuff.
"""

import sys
import argparse
import os
import re
import urllib.request
import multiprocessing

__author__ = "Shangjin Tang"
__copyright__ = "Copyright 2022 Shangjin Tang"
__license__ = "GPL"
__version__ = "1.2.0"
__date__ = "20210301"
__email__ = "shangjin.tang@gmail.com"


# def get_build_versions():
#     request = urllib.request.Request("https://source.android.com/setup/start/build-numbers")
#     response = None
#     try:
#         response = urllib.request.urlopen(request)
#     except Exception as e:
#         print(e.reason)
#     response_content = response.read().decode('utf-8')
#
#     latest_build_branch, latest_build_version = re.search("<td>android\-((\d+)\.\d+\.\d+\_r\d+)<\/td>",
#                                                           response_content).groups()
#     build_versions = {latest_build_version: latest_build_branch[0]}
#     for build_version in range(int(latest_build_version), 1, -1):
#         build_branch = re.search("<td>android\-({}\.\d+\.\d+\_r\d+)<\/td>".format(str(build_version)),
#                                  response_content).groups(1)
#         build_versions[str(build_version)] = build_branch[0]
#     return build_versions


def get_build_branches():
    request = urllib.request.Request("https://source.android.com/setup/start/build-numbers")
    response = None
    try:
        response = urllib.request.urlopen(request)
    except urllib.error.URLError as e:
        print(e.reason)
    build_branches = re.findall("<td>android\-(\d+\.\d+\.\d+\_r\d+)<\/td>", response.read().decode('utf-8'))
    build_branches.append('master')
    return build_branches


def main():
    if not os.path.exists(ARGS.dir):
        raise IOError(ARGS.dir + " not exists")
    os.chdir(ARGS.dir)

    branch = 'master' if ARGS.branch == 'master' else 'android-{}'.format(ARGS.branch)
    if not os.path.exists(branch):
        os.mkdir(branch)
    os.chdir(branch)

    os.system(
        "repo init --depth=1 -u https://android.googlesource.com/platform/manifest -b {}".format(branch))
    projects = []
    if ARGS.compress:
        if not os.path.exists("../{}-compressed".format(branch)):
            os.mkdir("../{}-compressed".format(branch))
        os.system("tar -czvf ../{}-compressed/.repo.tar.gz .repo".format(branch))

    repo_sync_return_code = 0
    if not ARGS.projects:
        ARGS.projects = ['*']
        # print(ARGS.projects)
    for project in ARGS.projects:
        project = project.replace('*', '[\w\/\-\_]+')
        with open('.repo/manifests/default.xml', 'r') as manifest:
            for line in manifest:
                if re.search('project path="({})"'.format(project), line):
                    projects.append(re.search('project path="({})"'.format(project), line).group(1))
    # print(projects)

    for project in projects:
        # do not sync for project "prebuilts/*" for it requires large disk
        project_topdir = project.split('/')[0]
        if not project_topdir in ARGS.excluded_topdirs:
            if not ARGS.included_topdirs or project_topdir in ARGS.included_topdirs:
                print("Syncing project: " + project)
                repo_sync_return_code = os.system("repo sync -c -j{} --no-clone-bundle {}".format(ARGS.jobs, project))
                if not repo_sync_return_code and ARGS.compress:
                    os.system("tar -czvf ../{}-compressed/{}.tar.gz * && rm -rf *".format(branch,
                                                                                          project.replace('/', '--')))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    build_branches = get_build_branches()
    parser.add_argument('-b', '--branch', choices=build_branches, default=build_branches[0],
                        metavar='BRANCH', help="e.g. {} (default) / master".format(build_branches[0]))
    parser.add_argument('-d', '--dir', default=".")
    parser.add_argument('-j', '--jobs', default="{}".format(multiprocessing.cpu_count()))
    parser.add_argument('-p', '--projects', default="", nargs='+')
    parser.add_argument('-c', '--compress', default=False, action='store_true')
    group = parser.add_mutually_exclusive_group()
    group.add_argument('-e', '--excluded_topdirs', default="prebuilts", nargs='+')
    group.add_argument('-i', '--included_topdirs', default="", nargs='+')
    ARGS = parser.parse_args()
    try:
        main()
    except KeyboardInterrupt:
        print('Keyboard Interrupt')
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
