#!/usr/bin/env python3

import sys
import argparse
import os
import re

__author__ = "Shangjin Tang"
__email__ = "shangjin.tang@gmail.com"
__copyright__ = "Copyright 2022 Shangjin Tang"
__license__ = "GPL"
__version__ = "1.0.0"

ARGS = None  # Get argument: ARGS.arg
LOG_FORMAT = "%(asctime)s    %(levelname)s    %(filename)s:%(lineno)s\n\t%(message)s"
logging.basicConfig(level=logging.DEBUG, format=LOG_FORMAT)


def main():
    pass


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter, description="")
    # Sample configurations:
    # parser.add_argument('-d', '--dir', default=".")
    # parser.add_argument('-p', '--project', default="", choices=['projectA', 'projectB'])
    # parser.add_argument('-f', '--flag', default=False, action='store_true')
    # group = parser.add_mutually_exclusive_group()
    # group.add_argument('--foo', action='store_true')
    # group.add_argument('--bar', action='store_false')
    ARGS = parser.parse_args()
    try:
        main()
    except KeyboardInterrupt:
        print('Interrupted')
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
