#!/usr/bin/env python3
"""
This is a docstring.
"""

import logging
import os
import sys

import typer
from pydantic import BaseModel, ValidationError, field_validator

__author__ = "Shangjin Tang"
__email__ = "shangjin.tang@gmail.com"
__copyright__ = "Copyright 2023 Shangjin Tang"
__license__ = "GPL"
__version__ = "1.0.0"

LOGGING_FORMAT = "%(asctime)s [%(levelname)s] %(filename)s:%(lineno)d - %(message)s"
LOGGING_DATEFMT = "%Y-%m-%d %H:%M:%S"
logging.basicConfig(
    level=logging.DEBUG,
    format=LOGGING_FORMAT,
    datefmt=LOGGING_DATEFMT,
)

app = typer.Typer()


@app.command()
def main(
    input_file: str = "",
    output_file: str = "",
):
    logging.debug(f"Input file: {input_file}")
    logging.debug(f"Output file: {output_file}")


if __name__ == "__main__":
    try:
        typer.run(main)
    except KeyboardInterrupt:
        typer.echo("Interrupted")
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
