#!/usr/bin/env bash

SCRIPT=$(basename $0)

usage() {
  echo "Usage:"
  echo "  $SCRIPT [black|red|green|yellow|blue|purple|cyan|white] [message]"
  echo "  - using bold: add 'b' prefix before color"
  echo "  - using underscore: add 'u' prefix before color"
  exit 1
}

if [ -z "$1" ]; then
  usage 1
fi
typeset -l COLOR="$1"
shift

# Regular Colors
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'

# Bold
BBLACK='\033[1;30m'
BRED='\033[1;31m'
BGREEN='\033[1;32m'
BYELLOW='\033[1;33m'
BBLUE='\033[1;34m'
BPURPLE='\033[1;35m'
BCYAN='\033[1;36m'
BWHITE='\033[1;37m'

# Underline
UBLACK='\033[4;30m'
URED='\033[4;31m'
UGREEN='\033[4;32m'
UYELLOW='\033[4;33m'
UBLUE='\033[4;34m'
UPURPLE='\033[4;35m'
UCYAN='\033[4;36m'
UWHITE='\033[4;37m'

MSG="$@"
COLOR=${COLOR,,}

regex="[bu]?(black|red|green|yellow|blue|purple|cyan|white)"
if [[ "${COLOR}" =~ $regex ]]; then
  COLORCODE=${COLOR^^}
  MSG='eval "echo -e \${$COLORCODE}${@}\${$COLORCODE}"'
else
  usage 1
fi
eval "${MSG}"
