#!/usr/bin/env bash

if [[ $(git rev-parse HEAD 2>&1 > /dev/null) ]]; then
    echo "fatal: Not a git repository"
    exit 1
fi

GSH_PREFIX="git show --color=always --pretty=oneline --name-only "

QUERY="${*:-}"
if [ -z $QUERY ]; then
    QUERY="HEAD"
fi

IFS=' ' read -ra selected < <(
    FZF_DEFAULT_COMMAND="$GSH_PREFIX $(printf %q "$QUERY") | sed '1d'" \
    fzf --ansi \
        --bind left:preview-page-up,right:preview-page-down,ctrl-/:toggle-preview \
        --header "git show ${QUERY}" \
        --preview "git show $QUERY --color=always --oneline -- {1}" \
        --preview-window 'up,75%,border-bottom,~1,+1/4' \
        --exit-0
)
[ -n "${selected[0]}" ] && fzf_git_log_follow "${selected[0]}"
