#!/usr/bin/env bash

if [[ $(git rev-parse HEAD 2>&1 > /dev/null) ]]; then
    echo "fatal: Not a git repository"
    exit 1
fi

GLF_PREFIX="git log --color=always --pretty=format:'%C(magenta)%h %C(green)(%cd) %C(red)<%an> %C(cyan)%d%Creset %s'\
    --abbrev-commit --date=format:'%Y-%m-%d %H:%M:%S' --follow -- "

QUERY="${*:-}"
echo $QUERY
if [ -z $QUERY ]; then
    QUERY="$({ find . -type d -print | sed 's!$!/!'; find . \! -type d; } |
        grep -v "./.git*" | sort | fzf)"
elif [ ! -f $QUERY ] && [ ! -d $QUERY ]; then
    # TODO: check if path $QUERY exists on HEAD commit
    echo "warning: path '${QUERY}' not in the working tree."
fi

IFS=' ' read -ra selected < <(
    FZF_DEFAULT_COMMAND="$GLF_PREFIX $(printf %q "$QUERY")" \
    fzf --ansi \
        --bind left:preview-page-up,right:preview-page-down,ctrl-/:toggle-preview \
        --delimiter ' ' \
        --header "git log --follow -- $QUERY" \
        --preview "git show {1} --color=always -- $QUERY" \
        --preview-window 'up,75%,border-bottom,~1,+1/4' \
        --no-sort \
        --exit-0
)
[ -n "${selected[0]}" ] && gsh "${selected[0]}"
