#!/usr/bin/env bash

######################################################################
# change to cscope directory
CSFILE=cscope.out

csdir=${PWD}
while [[ ! -f $csdir/$CSFILE ]] && [[ $csdir != '/' ]]; do
    csdir="$(dirname "$csdir")"
done
if [[ ! -f $csdir/$CSFILE ]]; then
    echo "error: file $CSFILE not found in current and parent dirs"
    exit 1
fi
cd $csdir

######################################################################

CSF_PREFIX="cscope -dL2 "  # Find functions called by this function

QUERY="${*:-}"

FORMAT='{ file=$1; symbol=$2; line=$3; $1=$2=$3="";
    printf "\033[35m%s\033[0m:\033[32m%s\033[0m:\t%s\n",file,line,$0; }'

IFS=: read -ra selected < <(
    FZF_DEFAULT_COMMAND="$CSF_PREFIX $(printf %q "$QUERY") | awk '$FORMAT' " \
    fzf --ansi \
        --color "hl:-1:underline:bold,hl+:-1:underline:bold:reverse" \
        --delimiter : \
        --header "functions called by '${QUERY}'" \
        --preview "bat --color=always {1} --highlight-line {2}" \
        --preview-window 'up,75%,border-bottom,~3,+{2}+0/4' \
        --exit-0
)
[ -n "${selected[0]}" ] && vim "${selected[0]}" "+${selected[1]}"
