#!/usr/bin/env bash
# shellcheck disable=1091,2034,2154

# Link: https://github.com/ralish/bash-script-template
# Depends on: ./bash_source

# Enable xtrace if the DEBUG environment variable is set
if [[ ${DEBUG-} =~ ^1|yes|true$ ]]; then
    set -o xtrace # Trace the execution of the script (debug)
fi

# Only enable these shell behaviours if we're not being sourced
# Approach via: https://stackoverflow.com/a/28776166/8787985
if ! (return 0 2> /dev/null); then
    # A better class of script...
    set -o errexit  # Exit on most errors (see the manual)
    set -o nounset  # Disallow expansion of unset variables
    set -o pipefail # Use last non-zero exit code in a pipeline
fi

# Enable errtrace or the error trap handler will not work as expected
set -o errtrace # Ensure the error trap handler is inherited

# DESC: Usage help
# ARGS: None
# OUTS: None
# shellcheck disable=2046
function script_usage() {
    cat << EOF
Usage: $(basename "$0") [OPTION]... -i [INPUT_STRING]
Add script usage description here.

Options:
     -h|--help                  Displays this help
     -v|--verbose               Displays verbose output
    -nc|--no-colour             Disables colour output
    -cr|--cron                  Run silently unless we encounter an error

Depends on file (to be sourced in this script):
    $(realpath $(dirname "${BASH_SOURCE[0]}"))/bash_source
EOF
}

# DESC: Parameter parser
# ARGS: $@ (optional): Arguments provided to the script
# OUTS: Variables indicating command-line parameters and options
function parse_params() {
    local param
    while [[ $# -gt 0 ]]; do
        param="$1"
        shift
        case $param in
            -h | --help)
                script_usage
                exit 0
                ;;
            -v | --verbose)
                verbose=true
                ;;
            -nc | --no-colour)
                no_colour=true
                ;;
            -cr | --cron)
                cron=true
                ;;
            -a | --all)
                download_all=true
                ;;
            *)
                script_exit "Invalid parameter was provided: $param" 1
                ;;
        esac
    done
}

DOWNLOAD_DIR=~/.gh_releases/download

function print_separate_line_wide_with_optional_arg() {
    pretty_print "============================================================" "$fg_yellow $ta_bold"
    if [ "$#" -ne 0 ]; then
        pretty_print "$*" "$fg_yellow $ta_bold"
    fi
}
function print_separate_line_with_optional_arg() {
    pretty_print "------------------------------------------------------------" "$fg_green $ta_bold"
    if [ "$#" -ne 0 ]; then
        pretty_print "$*" "$fg_green $ta_bold"
    fi
}

function binary_check() {
    local command_name="$1"
    if ! command -v "$command_name" &> /dev/null; then
        pretty_print "- $command_name does not exist" "$fg_yellow"
        return 1
    else
        pretty_print "- Available " "" "-" &&
            pretty_print "$command_name" "$fg_magenta"
        return 0
    fi
}

function env_check() {
    if ! binary_check "gh"; then
        pretty_print "ERROR: 'gh' is not available, please install it and make sure it's in PATH" "$fg_red $ta_bold"
        pretty_print "- See: https://github.com/cli/cli/releases/latest" "$fg_red"
        exit 1
    fi
    local ARCH
    ARCH=$(uname -m)
    if [[ $ARCH != "x86_64" ]]; then
        pretty_print "ERROR: this script does not support arch '${ARCH}'" "$fg_red $ta_bold"
        exit 1
    fi
}

function cleanup() {
    echo ""
    verbose_print "Downloading interrupted"
    if rm -f "$DOWNLOAD_DIR/$PATTERN"; then
        verbose_print "$PATTERN removed" "$fg_green"
    else
        pretty_print "$PATTERN removed error" "$fg_red"
    fi
    exit 130 # SIGINT
}

function try_download() {
    REPO="$1"
    PATTERN="$2"
    if ! find $DOWNLOAD_DIR -maxdepth 1 -type f -name "$PATTERN" -print -quit | grep -q . &> /dev/null; then
        pretty_print "  - $PATTERN: downloading" "$fg_green"
        pretty_print "- gh release download --dir $DOWNLOAD_DIR --repo $1 --pattern $2" "$fg_green"
        gh release download --dir "$DOWNLOAD_DIR" --repo "$REPO" --pattern "$PATTERN"
    else
        pretty_print "  - $PATTERN: exists" "$fg_blue"
    fi
}

# DESC: Main control flow
# ARGS: $@ (optional): Arguments provided to the script
# OUTS: None
function main() {
    trap script_trap_err ERR
    trap script_trap_exit EXIT
    trap cleanup SIGINT

    script_init "$@"
    parse_params "$@"
    cron_init
    colour_init
    #lock_init system

    # check environment
    print_separate_line_wide_with_optional_arg "ENV CHECK"
    env_check
    # prepare directories
    [[ ! -d $DOWNLOAD_DIR ]] && mkdir -p $DOWNLOAD_DIR

    print_separate_line_wide_with_optional_arg "Download"

    # nvim: https://github.com/neovim/neovim/releases/download
    if [[ -n ${download_all-} ]] || ! binary_check "nvim"; then
        print_separate_line_with_optional_arg nvim
        try_download "neovim/neovim" "nvim.appimage"
    fi

    # ast-grep: https://github.com/ast-grep/ast-grep/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "ast-grep"; then
        print_separate_line_with_optional_arg ast-grep
        try_download "ast-grep/ast-grep" "sg-x86_64-unknown-linux-gnu.zip"
    fi

    # bat: https://github.com/sharkdp/bat/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "bat"; then
        print_separate_line_with_optional_arg bat
        try_download "sharkdp/bat" "bat-*-x86_64-unknown-linux-musl.tar.gz"
    fi

    # delta: https://github.com/dandavison/delta/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "delta"; then
        try_download "dandavison/delta" "delta-*-x86_64-unknown-linux-musl.tar.gz"
    fi

    # dua: https://github.com/Byron/dua-cli/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "dua"; then
        try_download "Byron/dua-cli" "dua-*-x86_64-unknown-linux-musl.tar.gz"
    fi

    # fd: https://github.com/sharkdp/fd/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "fd"; then
        try_download "sharkdp/fd" "fd-*-x86_64-unknown-linux-musl.tar.gz"
    fi

    # hexyl: https://github.com/sharkdp/hexyl/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "hexyl"; then
        try_download "sharkdp/hexyl" "hexyl-*-x86_64-unknown-linux-musl.tar.gz"
    fi

    # hyperfine: https://github.com/sharkdp/hyperfine/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "hyperfine"; then
        try_download "sharkdp/hyperfine" "hyperfine-*-x86_64-unknown-linux-musl.tar.gz"
    fi

    # lazygit: https://github.com/jesseduffield/lazygit/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "lazygit"; then
        try_download "jesseduffield/lazygit" "lazygit_0.40.2_Linux_x86_64.tar.gz"
    fi

    # lsd: https://github.com/lsd-rs/lsd/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "lsd"; then
        try_download "lsd-rs/lsd" "lsd-*-x86_64-unknown-linux-musl.tar.gz"
    fi

    # macchina: https://github.com/Macchina-CLI/macchina/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "macchina"; then
        try_download "Macchina-CLI/macchina" "macchina-linux-x86_64"
    fi

    # ouch: https://github.com/ouch-org/ouch/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "ouch"; then
        try_download "ouch-org/ouch" "ouch-x86_64-unknown-linux-musl.tar.gz"
    fi

    # procs: https://github.com/dalance/procs/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "procs"; then
        try_download "dalance/procs" "procs-*-x86_64-linux.zip"
    fi

    # pueue & pueued: https://github.com/Nukesor/pueue/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "pueue"; then
        try_download "Nukesor/pueue" "pueued-linux-x86_64"
    fi
    if [[ -n ${download_all-} ]] || ! binary_check "pueued"; then
        try_download "Nukesor/pueued" "pueued-linux-x86_64"
    fi

    # rg: https://github.com/BurntSushi/ripgrep/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "rg"; then
        try_download "BurntSushi/ripgrep" "ripgrep-*-x86_64-unknown-linux-musl.tar.gz"
    fi

    # sd: https://github.com/chmln/sd/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "sd"; then
        try_download "chmln/sd" "sd-*-x86_64-unknown-linux-musl"
    fi

    # tldr: https://github.com/dbrgn/tealdeer/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "tldr"; then
        try_download "dbrgn/tealdeer" "tealdeer-linux-x86_64-musl"
    fi

    # tokei: https://github.com/XAMPPRocky/tokei/releases/latest
    if [[ -n ${download_all-} ]] || ! binary_check "tokei"; then
        try_download "XAMPPRocky/tokei" "tokei-x86_64-unknown-linux-gnu.tar.gz"
    fi
}

# shellcheck source=source.sh
source "$(dirname "${BASH_SOURCE[0]}")/bash_source"

# Invoke main with args if not sourced
# Approach via: https://stackoverflow.com/a/28776166/8787985
if ! (return 0 2> /dev/null); then
    main "$@"
fi

# vim: syntax=sh cc=120 tw=119 ts=4 sw=4 sts=4 et sr
