#!/usr/bin/env bash
#
# show file change in specific COMMIT using `git show`

# dependencies: fzf, delta

if [[ $(git rev-parse HEAD 2>&1 > /dev/null) ]]; then
    echo "fatal: Not a git repository"
    exit 1
fi

GSH_PREFIX="git show --color=always --pretty=oneline --name-only "

QUERY="${*:-}"
if [ -z $QUERY ]; then
    QUERY="$({
        git log --color --pretty=format:'%h (%cd) <%an> %d %s' --abbrev-commit --date=format:'%Y-%m-%d %H:%M:%S'
    } | fzf)"
fi

QUERY_HASH=$(echo "$QUERY" | awk '{print $1}')

IFS=' ' read -ra selected < <(
    FZF_DEFAULT_COMMAND="$GSH_PREFIX $(printf %q "$QUERY_HASH") | sed '1d'" \
        fzf --ansi \
        --bind left:preview-page-up,right:preview-page-down,ctrl-/:toggle-preview \
        --header "git show ${QUERY_HASH}" \
        --preview "git show $QUERY_HASH --color=always --oneline -- {1}" \
        --preview-window 'up,75%,border-bottom,~1,+1/4' \
        --exit-0
)
[ -n "${selected[0]}" ] && git show $QUERY_HASH --color=always --oneline -- "${selected[0]}" | delta --diff-so-fancy -s
