#!/bin/bash

# Colors
RESET=$(tput sgr0)
# RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
# YELLOW=$(tput setaf 3)
# BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
# ITALIC=$(tput sitm)
BOLD=$(tput bold)

# Usage example: $0 RobotoMono FiraCode

RELEASE_VER="v3.0.2"
DOWNLOAD_DIR=~/.fonts
NEED_TO_REFRESH_CACHE=false

function prepare_download() {
    if [[ ! -d ${DOWNLOAD_DIR} ]]; then
        mkdir -p ${DOWNLOAD_DIR}
    fi
}

function download() {
    # echo "Installing Nerd Fonts: $*"
    for font in "$@"; do
        if [[ ! $(ls "${DOWNLOAD_DIR}/${font}"*) ]] &> /dev/null; then
            echo "- ${BOLD}${CYAN}INFO${RESET} Downloading from https://github.com/ryanoasis/nerd-fonts/releases/download/${RELEASE_VER}/${font}.zip to ${DOWNLOAD_DIR} ..."
            curl -fL "https://github.com/ryanoasis/nerd-fonts/releases/download/${RELEASE_VER}/${font}.zip" -o "${font}.zip" && unzip -o "${font}.zip" -d "${DOWNLOAD_DIR}/$font" && rm -f ${font}.zip > /dev/null &&
                echo "- ${BOLD}${CYAN}INFO${RESET} Downloading ${BOLD}${MAGENTA}${font} Nerd Font${RESET} to ${DOWNLOAD_DIR} succeeded" ||
                echo "- ${BOLD}${RED}ERROR${RESET} Downloading ${BOLD}${MAGENTA}${font} Nerd Font${RESET} to ${DOWNLOAD_DIR} failed"
            NEED_TO_REFRESH_CACHE=true
        else
            DOWNLOAD_DIR_RELATIVE=$(echo "$DOWNLOAD_DIR" | sed "s|^$HOME|~|")
            echo "- ${BOLD}${GREEN}OK${RESET} ${BOLD}${MAGENTA}${font} Nerd Font${RESET} is already downloaded to ${CYAN}${DOWNLOAD_DIR_RELATIVE}${RESET}, skipping ..."
        fi
    done
}

function refresh_cache() {
    if [[ -d ~/.local/share/fonts ]]; then
        mkdir -p ~/.local/share/fonts
    fi
    cp -rf ${DOWNLOAD_DIR}/**/*.ttf ~/.local/share/fonts
    fc-cache -fv > /dev/null &&
        echo "- ${BOLD}${GREEN}OK${RESET} Font cache refreshed succeeded" ||
        echo "- ${BOLD}${RED}ERROR${RESET} Font cache refreshed failed"
}

function main() {
    prepare_download
    download $@
    if [[ -n ${WSL_DISTRO_NAME} ]]; then
        echo "${BOLD}${CYAN}NOTE${RESET} For WSL, please manually install fonts in Windows"
    else
        if $NEED_TO_REFRESH_CACHE; then
            refresh_cache
        fi
    fi
}

function print_usage() {
    echo "Usage: $(basename $0) Font1 [Font2 Font3 ...]"
    echo "    You can find the Fonts in https://github.com/ryanoasis/nerd-fonts/releases/tag/${RELEASE_VER}"
    echo "Example: $(basename $0) RobotoMono FiraCode"
}

if [[ $# = 0 ]]; then
    print_usage
    exit 0
elif [[ $1 = '-h' ]] || [[ $1 = '--help' ]]; then
    print_usage
    exit 0
else
    main $@
fi
