#!/bin/bash

# Usage example: $0 RobotoMono FiraCode

DOWNLOAD_DIR=~/.fonts
NEED_TO_REFRESH_CACHE=false

function prepare_download() {
    if [[ ! -d ${DOWNLOAD_DIR} ]]; then
        mkdir -p ${DOWNLOAD_DIR}
    fi
}

function download() {
    echo "Installing Nerd Fonts: $*"
    for font in "$@"; do
        if [[ ! $(ls "${DOWNLOAD_DIR}/${font}/${font}NerdFont"*) ]] &> /dev/null; then
            echo "  - Downloading from https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/${font}.zip ..."
            curl -fL "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/${font}.zip" -o "${font}.zip" && unzip -o "${font}.zip" -d "${DOWNLOAD_DIR}/$font" && rm -f ${font}.zip > /dev/null
            echo "  - Download ${font} to $DOWNLOAD_DIR complete"
            NEED_TO_REFRESH_CACHE=true
        else
            echo "  - ${font} Nerd Font is already downloaded, skipping ..."
        fi
    done
}

function refresh_cache() {
    if [[ -d ~/.local/share/fonts ]]; then
        mkdir -p ~/.local/share/fonts
    fi
    cp -rf ${DOWNLOAD_DIR}/**/*.ttf ~/.local/share/fonts
    fc-cache -fv > /dev/null
    echo "cache refreshed"
}

function main() {
    prepare_download
    download $@
    if [[ -n ${WSL_DISTRO_NAME} ]]; then
        echo "  Note: For WSL, please manually install font in Windows"
    else
        if $NEED_TO_REFRESH_CACHE; then
            refresh_cache
        fi
    fi
}

function print_usage() {
    echo "Usage: $(basename $0) Font1 [Font2 Font3 ...]"
    echo "    You can find the Fonts in https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0"
    echo "Example: $(basename $0) RobotoMono FiraCode"
}

if [[ $# = 0 ]]; then
    print_usage
    exit 0
elif [[ $1 = '-h' ]] || [[ $1 = '--help' ]]; then
    print_usage
    exit 0
else
    main $@
fi
