#!/usr/bin/env bash

DEBUG_FLAG=false

BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
RESET=$(tput sgr0)

check_env() {
    if [ -z ${RSYNC_SSH_USER} ] || [ -z ${RSYNC_SSH_HOST} ]; then
        echo 'Error: please set env ${RSYNC_SSH_USER} and ${RSYNC_SSH_HOST} before using this script.'
        exit 1
    fi
    if [[ ${RSYNC_SSH_USR} == "root" ]]; then
        echo "Warning: you are using root user, please use it with caution."
    fi
    if [ "${RSYNC_SSH_HOME+x}" != "x" ] || [ -z ${RSYNC_SSH_HOME} ]; then
        $DEBUG_FLAG && echo '$RSYNC_SSH_HOME is not set, set it to /home/$RSYNC_SSH_USER'
        export RSYNC_SSH_HOME=/home/${RSYNC_SSH_USER}
    fi
    if [ "${RSYNC_SSH_PORT+x}" != "x" ] || [ -z ${RSYNC_SSH_PORT} ]; then
        $DEBUG_FLAG && echo '$RSYNC_SSH_PORT is not set, set it to 22'
        export RSYNC_SSH_PORT=22
    fi
}

rsync_to_ssh_server() {
    local ARGS="${@}"
    echo "===================================================================================================="
    local TASK_ARR=($ARGS)
    local TASK_NUM=${#TASK_ARR[@]}
    local TASK_INDEX=0
    for ARG in $ARGS; do
        RELATIVE_PATH=$(realpath --relative-to=$(realpath ~) $(realpath ${ARG}))
        TASK_INDEX=$((TASK_INDEX + 1))
        local RSYNC_COMMAND="rsync ${RSYNC_FLAGS} -e 'ssh -i ~/.ssh/id_rsa -p ${RSYNC_SSH_PORT}' --relative ~/./${RELATIVE_PATH} ${RSYNC_SSH_USER}@${RSYNC_SSH_HOST}:${RSYNC_SSH_HOME}"
        echo "${GREEN}($TASK_INDEX/$TASK_NUM)${RESET}"
        $DEBUG_FLAG && echo "$RSYNC_COMMAND"
        $DEBUG_FLAG && echo "--------------------------------------------------------------------------------"
        echo "rsync: ${GREEN}~/${RELATIVE_PATH}${RESET} (local) => ${MAGENTA}${RSYNC_SSH_HOME}/${RELATIVE_PATH}${RESET} (remote)"
        echo "flags: ${RSYNC_FLAGS}"
        echo "--------------------------------------------------------------------------------"
        if [ ! -e ~/${RELATIVE_PATH} ]; then
            echo "Warning: the source ~/${RELATIVE_PATH} does not exist on local client, skipped."
        else
            eval $RSYNC_COMMAND
        fi
        echo "===================================================================================================="
    done
}

rsync_from_ssh_server() {
    local ARGS="${@}"
    echo "===================================================================================================="
    local TASK_ARR=($ARGS)
    local TASK_NUM=${#TASK_ARR[@]}
    local TASK_INDEX=0
    for ARG in $ARGS; do
        echo "$(dirname ${ARG})"
        # if $ARG not exist, we create it's upper directory first, otherwise $(realpath ${ARG})) would fail
        # TODO: remove the created directory if rsync fail
        if [[ ! -e ${ARG} ]]; then
            echo "local dir $(dirname ${ARG}) do not exist, create it first"
            mkdir -p $(dirname ${ARG})
        fi
        RELATIVE_PATH=$(realpath --relative-to=$(realpath ~) $(realpath ${ARG}))
        TASK_INDEX=$((TASK_INDEX + 1))
        if [[ -z ${RELATIVE_PATH} ]] || [[ ${RELATIVE_PATH} == '.' ]]; then
            echo "${RED}Fatal: sync all files to ~ is forbidden. exit...${RESET}"
            exit 1
        fi
        local RSYNC_COMMAND="rsync ${RSYNC_FLAGS} -e 'ssh -i ~/.ssh/id_rsa -p ${RSYNC_SSH_PORT}' --relative ${RSYNC_SSH_USER}@${RSYNC_SSH_HOST}:${RSYNC_SSH_HOME}/./${RELATIVE_PATH} ~"
        echo "${GREEN}($TASK_INDEX/$TASK_NUM)${RESET}"
        $DEBUG_FLAG && echo "$RSYNC_COMMAND"
        $DEBUG_FLAG && echo "--------------------------------------------------------------------------------"
        echo "rsync: ${GREEN}${RSYNC_SSH_HOME}/${RELATIVE_PATH}${RESET} (remote) => ${MAGENTA}~/${RELATIVE_PATH}${RESET} (local)"
        echo "flags: ${RSYNC_FLAGS}"
        echo "--------------------------------------------------------------------------------"
        if ssh -i ~/.ssh/id_rsa -p ${RSYNC_SSH_PORT} ${RSYNC_SSH_USER}@${RSYNC_SSH_HOST} [ ! -e ${RSYNC_SSH_HOME}/${RELATIVE_PATH} ]; then
            echo "Warning: the source ${RSYNC_SSH_HOME}/${RELATIVE_PATH} does not exist on remote server, skipped."
        else
            eval $RSYNC_COMMAND
        fi
        echo "===================================================================================================="
    done
}

rsync_ssh_server() {
    check_env
    case $1 in
        pull | push)
            RSYNC_FLAGS='-avzhP'
            ;;
        pull-update | push-update)
            RSYNC_FLAGS='-avzhP --update'
            ;;
        pull-delete | push-delete)
            RSYNC_FLAGS='-avzhP --delete'
            ;;
        *)
            echo "Error: we only allow '(pull|push)(-update|-delete)?' in first argument"
            exit 1
            ;;
    esac
    case $1 in
        pull | pull-update | pull-delete)
            rsync_from_ssh_server "${@:2}"
            ;;
        push | push-update | push-delete)
            rsync_to_ssh_server "${@:2}"
            ;;
        *) ;;
    esac
}

print_usage() {
    echo "Usage:"
    echo '$0 pull|push SYNC_PATH1 [SYNC_PATH2 [SYNC_PATH3 ...]]'
    echo '1. The envs ${RSYNC_SSH_USER} and ${RSYNC_SSH_HOST} must be set before using this script.'
    echo '2. The envs ${RSYNC_SSH_PORT} is optional, default:22'
    echo '3. The envs ${RSYNC_SSH_HOME} is optional, default:/home/${RSYNC_SSH_USER}'
    echo '4. Every SYNC_PATH must be a relative path to ~ (e.g. temp) or a path contains ~ (e.g. ~/temp)'
}
if [ $1 == "-h" ] || [ $1 == "--help" ]; then
    print_usage
else
    set -e
    rsync_ssh_server "$@"
fi
