#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No project specified, exit..."
    exit 1
fi
if [[ $1 == "--help" ]] || [[ $1 == "-h" ]]; then
    echo "Usage: $(basename $0) PROJECT_NAME [CODEDIR_TO_PLACE_UNDER_SRC...]"
    exit 1
fi

TOMCAT_ROOT=/opt/apache-tomcat
OPENGROK_ROOT=$HOME/opengrok
OPENGROK_JAR_PATH=$HOME/opengrok/dist/lib/opengrok.jar

PROJECT_NAME=$1
TOMCAT_WEBAPPS=${TOMCAT_ROOT}/webapps
OPENGROK_PROJECTS=${OPENGROK_ROOT}/projects

PROJECT_WEBXML=${TOMCAT_WEBAPPS}/${PROJECT_NAME}/WEB-INF/web.xml
PROJECT_ROOT=${OPENGROK_PROJECTS}/${PROJECT_NAME}

if [ ! -d ${TOMCAT_ROOT} ] || [ ! -d ${OPENGROK_PROJECTS} ]; then
    echo "fatal: environment error"
    exit 1
fi

if [ $# -ge 2 ]; then
    echo "########## Configure Tomcat Begin ##########"

    if [ ! -f ${PROJECT_WEBXML} ]; then
        echo "Tomcat: copy source.war to ${PROJECT_NAME}.war..."
        cp -f ${TOMCAT_WEBAPPS}/source.war ${TOMCAT_WEBAPPS}/${PROJECT_NAME}.war
        while [ ! -f ${PROJECT_WEBXML} ]; do
            echo "Tomcat: wait generate folder from ${PROJECT_NAME}.war .."
            sleep 3
        done
        echo "Tomcat: generate folder from ${PROJECT_NAME}.war succeed"
    fi

    tomcat_orig_config=$(echo /var/opengrok/etc/configuration.xml | sed 's_/_\\/_g')
    tomcat_target_config=$(echo ${PROJECT_ROOT}/etc/configuration.xml | sed 's_/_\\/_g')
    sed -i "s/${tomcat_orig_config}/${tomcat_target_config}/g" ${PROJECT_WEBXML}

    echo "########## Configure Tomcat End ##########"

    echo "########## Generate Project Filetree Begin ##########"

    if [ ! -d ${PROJECT_ROOT} ]; then
        cp -rf ${OPENGROK_PROJECTS}/project_example ${PROJECT_ROOT}
        echo "Filetree: copied from project_example"
    fi

    sed -i "s/project_example/${PROJECT_NAME}/g" ${PROJECT_ROOT}/etc/logging.properties

    if [ $# -ge 2 ] && [ -d ${PROJECT_ROOT}/src ]; then
        echo "Moving folder(s) to ${PROJECT_ROOT}/src/"
        mv ${@:2} ${PROJECT_ROOT}/src
    fi

    echo "########## Generate Project Filetree End ##########"
fi

echo "########## OpenGrok Project Deploy Begin ##########"
if [ -d ${PROJECT_ROOT} ]; then
    if [ ! "$(ls -A ${PROJECT_ROOT}/src)" ]; then
        echo "warning: directory is empty, exit..."
        exit 0
    fi

    echo "Deploying OpenGrok for project: ${PROJECT_NAME}"

    java -Djava.util.logging.config.file=${PROJECT_ROOT}/etc/logging.properties \
        -jar ${OPENGROK_JAR_PATH} \
        -c /usr/local/bin/ctags \
        -s ${PROJECT_ROOT}/src \
        -d ${PROJECT_ROOT}/data \
        -P \
        -W ${PROJECT_ROOT}/etc/configuration.xml \
        -U http://localhost:8080/${PROJECT_NAME}

    RESULT=$?
    if [ $RESULT -eq 0 ]; then
        echo "Deploy succeeded"
    else
        echo "Deploy failed"
    fi
fi
echo "########## OpenGrok Project Deploy Begin ##########"
