FROM jupyter/scipy-notebook:latest

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

LABEL maintainer="Shangjin Tang <shangjin.tang@gmail.com>"

EXPOSE 8888

# Install Tensorflow
# RUN mamba install --quiet --yes \
#     'tensorflow' && \
#     mamba clean --all -f -y && \
#     fix-permissions "${CONDA_DIR}" && \
#     fix-permissions "/home/${NB_USER}"

